### ISSUE TITLE
Make manual declaring configuration for mongobee

### ISSUE THREAD

**Issue by egnaf** [reckue/post-api#164]
Hi!
Please make the mongobee configuration through  application.yaml properties for manual declaring.
For example:
```yaml
# Local database information
MONGO_URI: mongodb://127.0.0.1
MONGO_PORT: 27017
MONGO_DBNAME: mongo-local
```

in configuration file:
```java
@Value("${file.directory}")
private String hello;
```

And please add this dependency:
```gradle
/* for properties */
implementation 'org.springframework.boot:spring-boot-configuration-processor'
```

It's all. Thanks. Good job!
